service: profile-update-lambda

provider:
  name: aws
  runtime: nodejs8.10
  profile: cda
  stage: ${opt:stage, 'dev'}
  custom:
    bucketConfig: "ccfs-profile-config"
    bucketChanges: "ccfs-profile-changes"
  environment:
    configBucket: ${self:provider.custom.bucketConfig}
    configKey: ${self:provider.stage}/config.json
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:provider.custom.bucketChanges}
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - ${self:provider.custom.bucketConfig}
            - "/*"

functions:
  addBeverage:
    handler: handler.addBeverage
    vpc:
      securityGroupIds:
        - sg-1c3cfe65
      subnetIds:
        - subnet-d67b9ffc
        - subnet-76439300
    events:
      - s3:
          bucket: ${self:provider.custom.bucketChanges}
          event: s3:ObjectCreated:*
          rules:
            - prefix: add/${self:provider.stage}/
            - suffix: .csv

  updateBeverage:
    handler: handler.updateBeverage
    vpc:
      securityGroupIds:
        - sg-1c3cfe65
      subnetIds:
        - subnet-d67b9ffc
        - subnet-76439300
    events:
      - s3:
          bucket: ${self:provider.custom.bucketChanges}
          event: s3:ObjectCreated:*
          rules:
            - prefix: update/${self:provider.stage}/
            - suffix: .csv
