service: profile-update-lambda

provider:
  name: aws
  runtime: nodejs8.10
  profile: cda
  stage: ${opt:stage, 'dev'}
  environment:
    configBucket: "ccfs-profile-config"
    configKey: ${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "ccfs-profile-changes"
            - "/*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "ccfs-profile-config"
            - "/*"

functions:
  addBeverage:
    handler: handler.addBeverage
    vpc:
      securityGroupIds:
        - sg-1c3cfe65
      subnetIds:
        - subnet-d67b9ffc
        - subnet-76439300
    events:
      - s3:
          bucket: "ccfs-profile-changes"
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

